WIP: Translate nip-49
nostr-jp/nips-ja pull request #101
Opened 2024-02-10 15:14 UTC by ocknamo

2024-02-10 15:17 UTC, ocknamo commented on 49.md
> +PASSWORD = ユーザから読み取る。
Note: 原文と比較すると「。」は不要ではないかとも思ったのですが、文末に「。」が必要とのlintルールがあったため追加しました。

2024-02-10 16:52 UTC, s3-odara requested changes

2024-02-10 16:52 UTC, s3-odara commented on 49.md
> +LOG\_N = ユーザーまたは実装者に、scryptのラウンド数として使用される2のべき乗を表す1バイト(eg.18は262,144を表す)を選択させる。数値が大きいほど、より多くの時間とより多くのメモリが必要になり、より強力な保護が提供される:
e.g.のピリオドが抜けています。個人的には「例えば」か「例: 」ぐらいに訳しても良い気がします。
```suggestion
LOG\_N = ユーザーまたは実装者に、scryptのラウンド数として使用される2のべき乗を表す1バイト(e.g. 18は262,144を表す)を選択させる。数値が大きいほど、より多くの時間とより多くのメモリが必要になり、より強力な保護が提供される:
```

2024-02-10 16:52 UTC, s3-odara commented on 49.md
> +パスワード = 'nostr'およびlog_n=16で復号化すると、次の16進数でエンコードされた秘密が生成される:
復号化ではなく復号が正しいと思います。
```suggestion
パスワード = 'nostr'およびlog_n=16で復号すると、次の16進数でエンコードされた秘密鍵が生成される:
```

2024-02-10 16:52 UTC, s3-odara commented on 49.md
> +1. 暗号化鍵は、対称暗号化アルゴリズムの仮定が有効であるように、均一で機能的にランダムなビット分布を持つパスワードから決定論的に作成する必要がある。そして
パスワードがランダムなビット分布を持つのではなくそうなるように導出するように見えます。
```suggestion
1. 暗号化鍵は、対象暗号化アルゴリズムの仮定が有効であるような、一様にランダムなビット分布を持つようにパスワードから決定論的に作成する必要がある。そして
```

2024-02-10 16:52 UTC, s3-odara commented on 49.md
> +2. 多くのパスワードを試して復号化する総当たり攻撃が大幅に阻止されるよう、低速で不可逆的なアルゴリズムをプロセスに挿入する必要がある。
```suggestion
2. 多くのパスワードを試して復号する総当たり攻撃が大幅に阻止されるよう、低速で不可逆的なアルゴリズムをプロセスに挿入する必要がある。
```

2024-02-11 09:39 UTC, s3-odara approved these changes

2024-02-11 09:42 UTC, merged

2024-02-11 14:59 UTC, ocknamo commented
:smile: