Update 23.md
nostr-jp/nips-ja pull request #24
Opened 2023-11-14 08:29 UTC by rira224

I translated NIP-23. It is my first pull-requests, so if there are any mistakes I'm sorry.

2023-11-14 08:52 UTC, rira224 commented on 23.md
> +他の投稿・記事・プロフィールへの参照は [NIP-27](27.md) に沿って行う必要がある。すなわち、 [NIP-21](21.md) で定義された `nostr:…` リンクをを使用し、任意でそのリンクに対応したタグを追加する(下記イベント例を参照)。
他の投稿・記事・プロフィールへの参照は [NIP-27](27.md) に沿って行う必要がある。すなわち、 [NIP-21](21.md) で定義された `nostr:…` リンクを使用し、任意でそのリンクに対応したタグを追加する(下記イベント例を参照)。

2023-11-14 08:58 UTC, rira224 reviewed
誤字修正

2023-11-14 09:49 UTC, darashi commented
#1 の「スタイルガイドなど」の項目に「ですます口調」と指定があります。

2023-11-14 09:55 UTC, erechorse requested changes
不慣れな中翻訳ありがとうございます。

- textlintの方の設定が不適切だったのでチェックが働いていないようですが、本文はですます口調で統一していただきたいです。
- 基本的には英単語の両端など、文中に空白は差し込まなくてもいいと思います。ただ、 (このように) 括弧の両端には半角スペースを挿入したほうが良いかもしれません。
- 原文9行目の翻訳で行数にずれが発生しているようです。対応する翻訳は同じ行に収めるようにお願いします。 [参考](https://zenn.dev/smikitky/articles/0d250f7367eda9#%E5%8E%9F%E6%96%87%E3%81%B8%E3%81%AE%E8%BF%BD%E5%BE%93)

2023-11-14 09:55 UTC, erechorse commented on 23.md
> +`draft` `optional` `author:fiatjaf` `translator:rira224`
```suggestion
`draft` `optional` `author:fiatjaf`
```
ほかの翻訳を確認しましたが、翻訳者の表記はいらないかもしれません。

2023-11-14 09:55 UTC, erechorse commented on 23.md
> +ロングフォームコンテント/長文投稿
```suggestion
長文投稿
```
どちらかに統一したほうが適切かと思われます。より語義が伝わりやすいのは「長文投稿」の方かと。

2023-11-14 09:55 UTC, erechorse commented on 23.md
> +### Editability (編集可能性)
```suggestion
### 編集可能性
```
意味が伝わるならば基本的には注記は不要かと思われます。

2023-11-14 10:42 UTC, rira224 reviewed
11行目の修正

2023-11-14 15:35 UTC, akiomik commented on 23.md
> +最終更新日については`.created_at`フィールドを使用し、[NIP-21](21.md)で定義された`t`タグ (タグ/ハッシュタグ、その記事が関連するトピック) を含めることが望ましいです。
```suggestion
最終更新日については`.created_at`フィールドを使用し、[NIP-12](12.md)で定義された`t`タグ (タグ/ハッシュタグ、その記事が関連するトピック) を含めることが望ましいです。
```

2023-11-14 15:37 UTC, akiomik commented on 23.md
> +長文投稿は編集可能であることを意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つ`d`タグを含める必要がある。各クライアントは、`d`タグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。
ですます調に統一

```suggestion
長文投稿は編集可能であることを意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つ`d`タグを含める必要があります。各クライアントは、`d`タグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。
```

2023-11-14 15:45 UTC, akiomik commented on 23.md
> +長文投稿は編集可能であることを意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つ`d`タグを含める必要がある。各クライアントは、`d`タグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。
> Clients should take care to only publish and read these events from relays that implement that.

の末尾の `that` は文脈からすると `d` タグではなく `parameterized replaceability feature` のことを指しているように思います🤔

2023-11-14 16:17 UTC, mattn commented on 23.md
> +- HTMLからMarkdownへの追加をサポートしてはなりません (MUST NOT)。
Markdown はゆるいフォーマットで、Markdown 書式の中に HTML を含ませる事ができるのですが、ここでの意味はそれをやってはならぬ、というものです。

2023-11-14 16:18 UTC, mattn commented on 23.md
> +- テキストの強制改行を行ってはなりません (MUST NOT) 。
80 カラム境界で開業するといった様な、段落の強制改行をしてはいけません。ですかね。

2023-11-15 10:43 UTC, darashi commented on 23.md
> +- `"published_at"`, 初版のUNIXタイムスタンプ(文字列化)
```suggestion
- `"published_at"`, 記事が初めて公開された時刻の(文字列化された)UNIX秒タイムスタンプ
```

unixタイムスタンプはJavaScript(とそこから派生しているJSON)ではミリ秒単位で扱われることも多く、そのため原文では秒であることを明言しているのだと思います。同様の記述はNIP-01にも繰り返し現れます。なので、それを訳に反映させました。

「初版」がドラフトの初版と受け取られる可能性があるかもしれないと思い、「published」を明示的に訳出して原文と逐語対応するようにしてみました。

「初版公開」とするともう少しコンパクトになるかもしれません。

```suggestion
- `"published_at"`, 初版公開時刻の(文字列化された)UNIX秒タイムスタンプ
```

2023-11-15 10:43 UTC, darashi commented on 23.md
> +その他メタデータフィールドは、必要に応じてイベントにタグを追加することができる。ここでは主要な4つのタグを標準化する(厳密には任意)。
```suggestion
その他メタデータフィールドは、必要に応じてイベントにタグを追加することができる。ここでは有用と思われる4つのタグを標準化する(厳密に任意)。
```

strictly optional の strictly は強意じゃないかと思います。 硬いし「任意」との組み合わせが変な感じがしますが「厳に任意」という感じでしょうか？　あるいは strict の「厳密」な感じからは少し離れますが「完全に任意」とかのほうが自然でしょうか。

that may be useful は「主要」というほど強くなさそうなので「有用と思われる」とするのはどうでしょう。

2023-11-15 10:45 UTC, darashi commented on 23.md
> +- `"published_at"`, 初版のUNIXタイムスタンプ (文字列化)
```suggestion
- `"published_at"`, 記事が初めて公開された時刻の(文字列化された)UNIX秒タイムスタンプ
```

unixタイムスタンプはJavaScript(とそこから派生しているJSON)ではミリ秒単位で扱われることも多く、そのため原文では秒であることを明言しているのだと思います。同様の記述はNIP-01にも繰り返し現れます。なので、それを訳に反映させました。

「初版」がドラフトの初版と受け取られる可能性があるかもしれないと思い、「published」を明示的に訳出して原文と逐語対応するようにしてみました。

「初版公開」とするともう少しコンパクトになるかもしれません。

```suggestion
- `"published_at"`, 初版公開時刻の(文字列化された)UNIX秒タイムスタンプ
```

2023-11-15 10:47 UTC, darashi commented on 23.md
> +その他メタデータフィールドは、必要に応じてイベントにタグを追加できます。ここでは主要な4つのタグを標準化します (厳密には任意)。
```suggestion
その他メタデータフィールドは、必要に応じてイベントにタグを追加することができる。ここでは有用と思われる4つのタグを標準化する(厳密に任意)。
```

strictly optional の strictly は強意じゃないかなと思います。「厳に任意」という感じでしょうか？硬いし「任意」との組み合わせが変な感じがしますが...。あるいは strict の「厳密」な感じからは少し離れますが「完全に任意」とかのほうが自然でしょうか。とはいえ「厳密に任意」は直訳としては安全かなという気がします。

that may be useful は「主要」というほど強くなさそうなので「有用と思われる」とするのはどうでしょう。

2023-11-18 17:41 UTC, rira224 commented
change.

2023-12-05 10:17 UTC, rira224 commented on 23.md
> +- テキストの強制改行を行ってはなりません (MUST NOT) 。
80 カラム境界で改行するといった様な、段落の強制改行をしてはいけません。

2023-12-05 10:17 UTC, rira224 commented on 23.md
> +長文投稿は編集可能であることを意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つ`d`タグを含める必要がある。各クライアントは、`d`タグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。
長文投稿は編集可能であることを意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つ`d`タグを含める必要があります。各クライアントは、`d`タグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。

2023-12-05 11:48 UTC, rira224 reviewed
changed.

2023-12-05 12:10 UTC, rira224 commented on 23.md
> +長文投稿は編集可能であることを意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つ`d`タグを含める必要があります。各クライアントは、`d`タグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。
長文投稿は編集する可能性を意図しているため、パラメータ化された置換可能機能を利用し、記事の識別子を持つdタグを含める必要があります。各クライアントは、dタグを実装したイベントのみをリレーに発行し、読み取るように注意すべきです。また同じ記事の古い版を非表示にすることにも注意すべきです。

2023-12-05 12:20 UTC, rira224 reviewed
checked

2023-12-06 09:57 UTC, erechorse commented on 23.md
> +- テキストの強制改行を行ってはなりません (MUST NOT) 。
```suggestion
- 80カラム境界で改行するといった様な、段落の強制改行をしてはいけません (MUST NOT) 。
```

2023-12-06 10:01 UTC, merged