NIP46を原文に追従
nostr-jp/nips-ja pull request #92
Opened 2024-01-16 03:25 UTC by s3-odara

NIP-46が書き直されていたので大幅に変わります。

2024-01-18 14:31 UTC, jiftechnify commented on 46.md
> +リモート署名器は以下の方法で接続トークンを生成する。
```suggestion
リモート署名器は以下の形式の接続トークンを生成する。
```

2024-01-18 14:36 UTC, jiftechnify commented on 46.md
> +イベントペイロードは[NIP-04](04.md)暗号化されたJSONRPC風 (以下のイベントフォーマットの`.content`内でその形式を指定される) のJSON blobである。
```suggestion
イベントペイロードは[NIP-04](04.md)暗号化されたJSONRPC風のJSON blobである (その形式は下記のイベントフォーマットの`.content`内で指定される) 。
```

2024-01-18 14:39 UTC, jiftechnify commented on 46.md
> +### 方法
```suggestion
### メソッド
```
この項はNIP-46で用いられるRPCメソッドのリファレンスなので、メソッド名にあたる部分は訳さないのが妥当かと思います。

2024-01-18 14:41 UTC, jiftechnify commented on 46.md
> +イベントペイロードは[NIP-04](04.md)暗号化されたJSONRPC風 (以下のイベントフォーマットの`.content`内でその形式を指定される) のJSON blobである。
括弧書きが文中に割り込むと読みづらいので、原文同様に文末に置いたほうが良さそうです。

2024-01-26 14:35 UTC, s3-odara commented on 46.md
> +### 方法
提案ありがとうございます。

2024-01-27 08:24 UTC, jiftechnify requested changes

2024-01-27 08:24 UTC, jiftechnify commented on 46.md
> +- **接続**
```suggestion
- **connect**
```
Methods節の各項目の名前は、アプリと署名器の間でやりとりするRPCのメソッド名そのものとなっているため、これを日本語に訳すべきではありません。get_public_key以降も同様です。

2024-01-27 09:14 UTC, s3-odara commented on 46.md
> +- **接続**
確かにそうでした。ありがとうございます。

2024-01-27 14:03 UTC, jiftechnify approved these changes

2024-01-27 14:04 UTC, merged